version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd frontend
      - export REACT_APP_BACKEND_URL=/api
      - npm install
      - npm run build
artifacts:
  files: "**/*"
  base-directory: frontend/build