version: "3.3"
services:
  frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports: 
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URI: http://192.168.99.101:8080

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: backend.dockerfile 
    ports:
      - 8080:8080