version: "3.3"
services:
  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports: 
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080/api

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080